# Generated by Django 5.1.5 on 2025-01-18 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_terminales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='gestion_terminales.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('estacionado', 'Estacionado'), ('en ruta', 'En Ruta')], max_length=20)),
                ('tiempo_max_permitido', models.IntegerField()),
                ('tiempo_excedido', models.DurationField(blank=True, null=True)),
                ('anden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_terminales.anden')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='gestion_terminales.empresa')),
            ],
        ),
    ]
