# Generated by Django 5.1.5 on 2025-01-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_terminales', '0002_empresa_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
