# Generated by Django 5.1.5 on 2025-01-18 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_terminales', '0004_bus_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusEstacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llegada', models.DateTimeField()),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_terminales.bus')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_terminales.terminal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
