# Generated by Django 5.1.5 on 2025-01-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_terminales', '0006_bus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anden',
            name='estado',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=15),
        ),
    ]
